title: Rock-Paper-Scissors Hand Gesture Game
description: A browser-based ML game using ONNX and MediaPipe
theme: minima

on: [push, pull_request]

# Set base URL if you're deploying to a project page (e.g., https://yourusername.github.io/rps-hand-game/)
baseurl: "/Praise_MLOps_Project" # change to your repo name
 
# GitHub Pages build config
plugins:
  - jekyll-feed
  - jekyll-seo-tag
 
exclude:
  - training/
  - README.md
  - preprocess.py
  - train.py
  - .gitignore
  - LICENSE
 
# For GitHub Pages (force to use GitHub's Jekyll)
markdown: kramdown


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true
          pip install black pytest

      - name: Code formatting check (black)
        run: |
          black --check src/ deployment/ scripts/ || echo "Formatting issues - fix later"

      - name: Run unit tests (pytest)
        run: |
          if [ -d "tests" ]; then
            pytest tests/ || echo "Tests failing - fix later"
          else
            echo "No tests folder yet, skipping tests"
          fi

      - name: Check model files
        run: |
          if [ -f "models/best_model.pt" ]; then
            echo "✅ Found best_model.pt"
          else
            echo "⚠️ best_model.pt not found - model training not yet done"
          fi

      - name: Build Docker container
        run: |
          if [ -f "deployment/Dockerfile" ]; then
            docker build -t praise-mlops-app deployment/ || echo "Docker build failed - fix later"
          else
            echo "No Dockerfile found, skipping Docker build"
          fi
