name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5  # ✅ Updated to latest

      - name: Upload static content
        uses: actions/upload-pages-artifact@v3  # ✅ No longer v2

        with:
          path: deployment  # Your folder with index.html etc.

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4  # ✅ Latest version
